version: '3.7'

services:
  api:
    image: dnyf-group-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    networks:
      dnyfcomposite:
        aliases:
          - dnyf-groups-microservice
      dnyfnet:
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dbuser
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuser
      - MYSQL_DATABASE=dnyf-group-db
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    networks:
      dnyfcomposite:
      dnyfnet:
        aliases:
        - dnyf-group-db

volumes:
  mysql:
  mysql_config:

networks:
  dnyfnet:
  dnyfcomposite:
    external: true
