version: '3.4'

services:
  api:
    image: dnyf-group-api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload"]
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:14.5-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=dbuser
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=dnyf-group-db
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
